---
title: "R Project 1 - Hello R"
author: "Iryna Dovzhuk"
date: "9/16/2020"
output: 
  html_document: 
    fig_width: 5
    fig_height: 6
    highlight: espresso
    theme: yeti
---
```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```

# A data frame for datasaurus_dozen has 1846 rows and 3 variables. The 3 variables are: dataset, x-values, and y-values. 

```{r plot-dino, fig.height5, fig.width=4}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

```{r plot-star}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
 
```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```

```{r plot-circle}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-circle}
circle_data %>%
  summarize(r = cor(x, y))
```

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+ geom_point()+ facet_wrap(~ dataset, ncol = 3) + theme(legend.position = "none")
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x,y)) %>%
  print(13)
```